{{- if and .Values.app.enabled .Values.autoscaling.enabled }}
{{- $fullName := include "app.fullName" . -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.autoscaling.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
{{- with .Values.autoscaling.cpu }}
    - type: Resource
      resource:
        name: cpu
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.autoscaling.memory }}
    - type: Resource
      resource:
        name: memory
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
